name: .NET CI

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  create-pull-request:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base develop \
            --head "${{ github.ref_name }}" \
            --title "PR - ${{ github.ref_name }}" \
            --body "Pull Request criada automaticamente após sucesso da pipeline CI em branch ${{ github.ref_name }}." \